//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Logic.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Password { get; set; }
        public string PasswordVerificationToken { get; set; }
    
        public virtual User User { get; set; }
    }
}
